package conversation

import (
	"context"
	"strings"
	"time"
	"unicode/utf8"
)

const chatTitleMaxRunes = 60

// TokenUsage contains model token consumption accumulated for a chat.
type TokenUsage struct {
	// InputTokens is the number of prompt tokens consumed by chat completions.
	InputTokens int64 `json:"input_tokens"`
	// OutputTokens is the number of completion tokens generated by chat completions.
	OutputTokens int64 `json:"output_tokens"`
	// TotalTokens is the total number of tokens reported by the model provider.
	TotalTokens int64 `json:"total_tokens"`
}

// Add accumulates another usage sample.
func (u *TokenUsage) Add(other TokenUsage) {
	if u == nil {
		return
	}
	u.InputTokens += other.InputTokens
	u.OutputTokens += other.OutputTokens
	u.TotalTokens += other.TotalTokens
}

// IsZero reports whether the provider returned no token usage.
func (u TokenUsage) IsZero() bool {
	return u.InputTokens == 0 && u.OutputTokens == 0 && u.TotalTokens == 0
}

// Chat is a persisted assistant conversation.
type Chat struct {
	// ID identifies the conversation.
	ID string `json:"id"`
	// Title is derived from the first user message.
	Title string `json:"title"`
	// CreatedAt is the timestamp when the chat was first persisted.
	CreatedAt time.Time `json:"created_at"`
	// UpdatedAt is the timestamp of the latest persisted message.
	UpdatedAt time.Time `json:"updated_at"`
	// Turns contains the full user-visible conversation history.
	Turns []Turn `json:"messages"`
	// Usage contains aggregate token consumption for successful chat completions.
	Usage *TokenUsage `json:"token_usage,omitempty"`
}

// ChatSummary contains metadata required to render the chat list.
type ChatSummary struct {
	// ID identifies the conversation.
	ID string `json:"id"`
	// Title is derived from the first user message.
	Title string `json:"title"`
	// CreatedAt is the timestamp when the chat was first persisted.
	CreatedAt time.Time `json:"created_at"`
	// UpdatedAt is the timestamp of the latest persisted message.
	UpdatedAt time.Time `json:"updated_at"`
	// Usage contains aggregate token consumption for the chat.
	Usage *TokenUsage `json:"token_usage,omitempty"`
}

// HistoryStorage persists complete assistant chats independently from the in-memory context cache.
type HistoryStorage interface {
	// ReadChats returns persisted chat metadata ordered by latest update first.
	ReadChats(ctx context.Context) ([]ChatSummary, error)
	// ReadChat returns a persisted chat by conversation ID.
	ReadChat(ctx context.Context, id string) (Chat, bool, error)
	// SaveTurns appends turns and accumulates model token usage atomically.
	SaveTurns(ctx context.Context, id string, usage TokenUsage, turns ...Turn) error
}

func buildChatTitle(turns []Turn) string {
	for _, turn := range turns {
		if turn.Role != "user" {
			continue
		}
		title := strings.Join(strings.Fields(turn.Content), " ")
		if title == "" {
			continue
		}
		if utf8.RuneCountInString(title) <= chatTitleMaxRunes {
			return title
		}
		runes := []rune(title)
		return strings.TrimSpace(string(runes[:chatTitleMaxRunes])) + "…"
	}
	return "New chat"
}
