// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mock.go -package=deployer
//

// Package deployer is a generated GoMock package.
package deployer

import (
	context "context"
	reflect "reflect"

	compose "github.com/swarm-deploy/swarm-deploy/internal/compose"
	gomock "go.uber.org/mock/gomock"
)

// MockStackDeployer is a mock of StackDeployer interface.
type MockStackDeployer struct {
	ctrl     *gomock.Controller
	recorder *MockStackDeployerMockRecorder
	isgomock struct{}
}

// MockStackDeployerMockRecorder is the mock recorder for MockStackDeployer.
type MockStackDeployerMockRecorder struct {
	mock *MockStackDeployer
}

// NewMockStackDeployer creates a new mock instance.
func NewMockStackDeployer(ctrl *gomock.Controller) *MockStackDeployer {
	mock := &MockStackDeployer{ctrl: ctrl}
	mock.recorder = &MockStackDeployerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStackDeployer) EXPECT() *MockStackDeployerMockRecorder {
	return m.recorder
}

// DeployStack mocks base method.
func (m *MockStackDeployer) DeployStack(ctx context.Context, stackName, composePath string, services []compose.Service) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeployStack", ctx, stackName, composePath, services)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeployStack indicates an expected call of DeployStack.
func (mr *MockStackDeployerMockRecorder) DeployStack(ctx, stackName, composePath, services any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeployStack", reflect.TypeOf((*MockStackDeployer)(nil).DeployStack), ctx, stackName, composePath, services)
}
