// Code generated by MockGen. DO NOT EDIT.
// Source: internal/entrypoints/mcpserver/tools/types.go
//
// Generated by this command:
//
//	mockgen -source=internal/entrypoints/mcpserver/tools/types.go -destination=/tmp/mock_tools_all.go -package=tools
//

package tools

import (
	reflect "reflect"

	githosting "github.com/swarm-deploy/swarm-deploy/internal/githosting"
	gomock "go.uber.org/mock/gomock"
)

// MockGitHostingProviderManager is a mock of GitHostingProviderManager interface.
type MockGitHostingProviderManager struct {
	ctrl     *gomock.Controller
	recorder *MockGitHostingProviderManagerMockRecorder
	isgomock struct{}
}

// MockGitHostingProviderManagerMockRecorder is the mock recorder for MockGitHostingProviderManager.
type MockGitHostingProviderManagerMockRecorder struct {
	mock *MockGitHostingProviderManager
}

// NewMockGitHostingProviderManager creates a new mock instance.
func NewMockGitHostingProviderManager(ctrl *gomock.Controller) *MockGitHostingProviderManager {
	mock := &MockGitHostingProviderManager{ctrl: ctrl}
	mock.recorder = &MockGitHostingProviderManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitHostingProviderManager) EXPECT() *MockGitHostingProviderManagerMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockGitHostingProviderManager) Get(uri string) (*githosting.ReferencedProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", uri)
	ret0, _ := ret[0].(*githosting.ReferencedProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockGitHostingProviderManagerMockRecorder) Get(uri any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockGitHostingProviderManager)(nil).Get), uri)
}
