// Code generated by MockGen. DO NOT EDIT.
// Source: internal/modules/assistant/tools/types.go
//
// Generated by this command:
//
//	mockgen -source=internal/modules/assistant/tools/types.go -destination=internal/modules/assistant/tools/mocks.go -package=tools
//

// Package tools is a generated GoMock package.
package tools

import (
	context "context"
	net "net"
	reflect "reflect"

	githosting "github.com/swarm-deploy/swarm-deploy/internal/githosting"
	history "github.com/swarm-deploy/swarm-deploy/internal/modules/event/history"
	differ "github.com/swarm-deploy/swarm-deploy/internal/modules/gitops/differ"
	diff "github.com/swarm-deploy/swarm-deploy/internal/modules/gitops/differ/diff"
	git "github.com/swarm-deploy/swarm-deploy/internal/modules/gitops/git"
	model "github.com/swarm-deploy/swarm-deploy/internal/modules/recommendations/model"
	modelstore "github.com/swarm-deploy/swarm-deploy/internal/modules/recommendations/modelstore"
	model0 "github.com/swarm-deploy/swarm-deploy/internal/modules/resources/service/model"
	registry "github.com/swarm-deploy/swarm-deploy/internal/registry"
	swarm "github.com/swarm-deploy/swarm-deploy/internal/swarm"
	gomock "go.uber.org/mock/gomock"
)

// MockHistoryReader is a mock of HistoryReader interface.
type MockHistoryReader struct {
	ctrl     *gomock.Controller
	recorder *MockHistoryReaderMockRecorder
	isgomock struct{}
}

// MockHistoryReaderMockRecorder is the mock recorder for MockHistoryReader.
type MockHistoryReaderMockRecorder struct {
	mock *MockHistoryReader
}

// NewMockHistoryReader creates a new mock instance.
func NewMockHistoryReader(ctrl *gomock.Controller) *MockHistoryReader {
	mock := &MockHistoryReader{ctrl: ctrl}
	mock.recorder = &MockHistoryReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHistoryReader) EXPECT() *MockHistoryReaderMockRecorder {
	return m.recorder
}

// ReadRecent mocks base method.
func (m *MockHistoryReader) ReadRecent(ctx context.Context, options history.QueryOptions) ([]history.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadRecent", ctx, options)
	ret0, _ := ret[0].([]history.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadRecent indicates an expected call of ReadRecent.
func (mr *MockHistoryReaderMockRecorder) ReadRecent(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadRecent", reflect.TypeOf((*MockHistoryReader)(nil).ReadRecent), ctx, options)
}

// MockSyncTrigger is a mock of SyncTrigger interface.
type MockSyncTrigger struct {
	ctrl     *gomock.Controller
	recorder *MockSyncTriggerMockRecorder
	isgomock struct{}
}

// MockSyncTriggerMockRecorder is the mock recorder for MockSyncTrigger.
type MockSyncTriggerMockRecorder struct {
	mock *MockSyncTrigger
}

// NewMockSyncTrigger creates a new mock instance.
func NewMockSyncTrigger(ctrl *gomock.Controller) *MockSyncTrigger {
	mock := &MockSyncTrigger{ctrl: ctrl}
	mock.recorder = &MockSyncTriggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncTrigger) EXPECT() *MockSyncTriggerMockRecorder {
	return m.recorder
}

// Manual mocks base method.
func (m *MockSyncTrigger) Manual(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Manual", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Manual indicates an expected call of Manual.
func (mr *MockSyncTriggerMockRecorder) Manual(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Manual", reflect.TypeOf((*MockSyncTrigger)(nil).Manual), ctx)
}

// MockNodesReader is a mock of NodesReader interface.
type MockNodesReader struct {
	ctrl     *gomock.Controller
	recorder *MockNodesReaderMockRecorder
	isgomock struct{}
}

// MockNodesReaderMockRecorder is the mock recorder for MockNodesReader.
type MockNodesReaderMockRecorder struct {
	mock *MockNodesReader
}

// NewMockNodesReader creates a new mock instance.
func NewMockNodesReader(ctrl *gomock.Controller) *MockNodesReader {
	mock := &MockNodesReader{ctrl: ctrl}
	mock.recorder = &MockNodesReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNodesReader) EXPECT() *MockNodesReaderMockRecorder {
	return m.recorder
}

// ReadAll mocks base method.
func (m *MockNodesReader) ReadAll(ctx context.Context) ([]swarm.Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAll", ctx)
	ret0, _ := ret[0].([]swarm.Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAll indicates an expected call of ReadAll.
func (mr *MockNodesReaderMockRecorder) ReadAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAll", reflect.TypeOf((*MockNodesReader)(nil).ReadAll), ctx)
}

// MockPluginReader is a mock of PluginReader interface.
type MockPluginReader struct {
	ctrl     *gomock.Controller
	recorder *MockPluginReaderMockRecorder
	isgomock struct{}
}

// MockPluginReaderMockRecorder is the mock recorder for MockPluginReader.
type MockPluginReaderMockRecorder struct {
	mock *MockPluginReader
}

// NewMockPluginReader creates a new mock instance.
func NewMockPluginReader(ctrl *gomock.Controller) *MockPluginReader {
	mock := &MockPluginReader{ctrl: ctrl}
	mock.recorder = &MockPluginReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPluginReader) EXPECT() *MockPluginReaderMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockPluginReader) List(ctx context.Context) ([]swarm.Plugin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]swarm.Plugin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPluginReaderMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPluginReader)(nil).List), ctx)
}

// MockServicesReader is a mock of ServicesReader interface.
type MockServicesReader struct {
	ctrl     *gomock.Controller
	recorder *MockServicesReaderMockRecorder
	isgomock struct{}
}

// MockServicesReaderMockRecorder is the mock recorder for MockServicesReader.
type MockServicesReaderMockRecorder struct {
	mock *MockServicesReader
}

// NewMockServicesReader creates a new mock instance.
func NewMockServicesReader(ctrl *gomock.Controller) *MockServicesReader {
	mock := &MockServicesReader{ctrl: ctrl}
	mock.recorder = &MockServicesReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServicesReader) EXPECT() *MockServicesReaderMockRecorder {
	return m.recorder
}

// ReadAll mocks base method.
func (m *MockServicesReader) ReadAll(ctx context.Context) ([]model0.Info, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAll", ctx)
	ret0, _ := ret[0].([]model0.Info)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAll indicates an expected call of ReadAll.
func (mr *MockServicesReaderMockRecorder) ReadAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAll", reflect.TypeOf((*MockServicesReader)(nil).ReadAll), ctx)
}

// MockRecommendationsReader is a mock of RecommendationsReader interface.
type MockRecommendationsReader struct {
	ctrl     *gomock.Controller
	recorder *MockRecommendationsReaderMockRecorder
	isgomock struct{}
}

// MockRecommendationsReaderMockRecorder is the mock recorder for MockRecommendationsReader.
type MockRecommendationsReaderMockRecorder struct {
	mock *MockRecommendationsReader
}

// NewMockRecommendationsReader creates a new mock instance.
func NewMockRecommendationsReader(ctrl *gomock.Controller) *MockRecommendationsReader {
	mock := &MockRecommendationsReader{ctrl: ctrl}
	mock.recorder = &MockRecommendationsReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecommendationsReader) EXPECT() *MockRecommendationsReaderMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockRecommendationsReader) List(ctx context.Context, filter modelstore.ListFilter) ([]model.Recommendation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]model.Recommendation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRecommendationsReaderMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRecommendationsReader)(nil).List), ctx, filter)
}

// MockDNSResolver is a mock of DNSResolver interface.
type MockDNSResolver struct {
	ctrl     *gomock.Controller
	recorder *MockDNSResolverMockRecorder
	isgomock struct{}
}

// MockDNSResolverMockRecorder is the mock recorder for MockDNSResolver.
type MockDNSResolverMockRecorder struct {
	mock *MockDNSResolver
}

// NewMockDNSResolver creates a new mock instance.
func NewMockDNSResolver(ctrl *gomock.Controller) *MockDNSResolver {
	mock := &MockDNSResolver{ctrl: ctrl}
	mock.recorder = &MockDNSResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDNSResolver) EXPECT() *MockDNSResolverMockRecorder {
	return m.recorder
}

// LookupIPAddr mocks base method.
func (m *MockDNSResolver) LookupIPAddr(ctx context.Context, host string) ([]net.IPAddr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupIPAddr", ctx, host)
	ret0, _ := ret[0].([]net.IPAddr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupIPAddr indicates an expected call of LookupIPAddr.
func (mr *MockDNSResolverMockRecorder) LookupIPAddr(ctx, host any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupIPAddr", reflect.TypeOf((*MockDNSResolver)(nil).LookupIPAddr), ctx, host)
}

// MockImageVersionResolver is a mock of ImageVersionResolver interface.
type MockImageVersionResolver struct {
	ctrl     *gomock.Controller
	recorder *MockImageVersionResolverMockRecorder
	isgomock struct{}
}

// MockImageVersionResolverMockRecorder is the mock recorder for MockImageVersionResolver.
type MockImageVersionResolverMockRecorder struct {
	mock *MockImageVersionResolver
}

// NewMockImageVersionResolver creates a new mock instance.
func NewMockImageVersionResolver(ctrl *gomock.Controller) *MockImageVersionResolver {
	mock := &MockImageVersionResolver{ctrl: ctrl}
	mock.recorder = &MockImageVersionResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageVersionResolver) EXPECT() *MockImageVersionResolverMockRecorder {
	return m.recorder
}

// ResolveActualVersion mocks base method.
func (m *MockImageVersionResolver) ResolveActualVersion(ctx context.Context, image string) (registry.ImageVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveActualVersion", ctx, image)
	ret0, _ := ret[0].(registry.ImageVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveActualVersion indicates an expected call of ResolveActualVersion.
func (mr *MockImageVersionResolverMockRecorder) ResolveActualVersion(ctx, image any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveActualVersion", reflect.TypeOf((*MockImageVersionResolver)(nil).ResolveActualVersion), ctx, image)
}

// MockGitRepository is a mock of GitRepository interface.
type MockGitRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGitRepositoryMockRecorder
	isgomock struct{}
}

// MockGitRepositoryMockRecorder is the mock recorder for MockGitRepository.
type MockGitRepositoryMockRecorder struct {
	mock *MockGitRepository
}

// NewMockGitRepository creates a new mock instance.
func NewMockGitRepository(ctrl *gomock.Controller) *MockGitRepository {
	mock := &MockGitRepository{ctrl: ctrl}
	mock.recorder = &MockGitRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitRepository) EXPECT() *MockGitRepositoryMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockGitRepository) List(ctx context.Context, limit int) ([]git.CommitMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit)
	ret0, _ := ret[0].([]git.CommitMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockGitRepositoryMockRecorder) List(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockGitRepository)(nil).List), ctx, limit)
}

// Show mocks base method.
func (m *MockGitRepository) Show(ctx context.Context, commitHash string) (git.Commit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Show", ctx, commitHash)
	ret0, _ := ret[0].(git.Commit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Show indicates an expected call of Show.
func (mr *MockGitRepositoryMockRecorder) Show(ctx, commitHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Show", reflect.TypeOf((*MockGitRepository)(nil).Show), ctx, commitHash)
}

// MockCommitDiffer is a mock of CommitDiffer interface.
type MockCommitDiffer struct {
	ctrl     *gomock.Controller
	recorder *MockCommitDifferMockRecorder
	isgomock struct{}
}

// MockCommitDifferMockRecorder is the mock recorder for MockCommitDiffer.
type MockCommitDifferMockRecorder struct {
	mock *MockCommitDiffer
}

// NewMockCommitDiffer creates a new mock instance.
func NewMockCommitDiffer(ctrl *gomock.Controller) *MockCommitDiffer {
	mock := &MockCommitDiffer{ctrl: ctrl}
	mock.recorder = &MockCommitDifferMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommitDiffer) EXPECT() *MockCommitDifferMockRecorder {
	return m.recorder
}

// Compare mocks base method.
func (m *MockCommitDiffer) Compare(composeFiles []differ.ComposeFile) (diff.Diff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compare", composeFiles)
	ret0, _ := ret[0].(diff.Diff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Compare indicates an expected call of Compare.
func (mr *MockCommitDifferMockRecorder) Compare(composeFiles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compare", reflect.TypeOf((*MockCommitDiffer)(nil).Compare), composeFiles)
}

// MockGitHostingProviderManager is a mock of GitHostingProviderManager interface.
type MockGitHostingProviderManager struct {
	ctrl     *gomock.Controller
	recorder *MockGitHostingProviderManagerMockRecorder
	isgomock struct{}
}

// MockGitHostingProviderManagerMockRecorder is the mock recorder for MockGitHostingProviderManager.
type MockGitHostingProviderManagerMockRecorder struct {
	mock *MockGitHostingProviderManager
}

// NewMockGitHostingProviderManager creates a new mock instance.
func NewMockGitHostingProviderManager(ctrl *gomock.Controller) *MockGitHostingProviderManager {
	mock := &MockGitHostingProviderManager{ctrl: ctrl}
	mock.recorder = &MockGitHostingProviderManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitHostingProviderManager) EXPECT() *MockGitHostingProviderManagerMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockGitHostingProviderManager) Get(uri string) (*githosting.ReferencedProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", uri)
	ret0, _ := ret[0].(*githosting.ReferencedProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockGitHostingProviderManagerMockRecorder) Get(uri any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockGitHostingProviderManager)(nil).Get), uri)
}
