// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ListStacks implements listStacks operation.
//
// GET /api/v1/stacks
func (UnimplementedHandler) ListStacks(ctx context.Context) (r *StacksResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ReceiveGitWebhook implements receiveGitWebhook operation.
//
// POST /api/v1/webhooks/git
func (UnimplementedHandler) ReceiveGitWebhook(ctx context.Context, req OptGitWebhookPayload, params ReceiveGitWebhookParams) (r ReceiveGitWebhookRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TriggerSync implements triggerSync operation.
//
// POST /api/v1/sync
func (UnimplementedHandler) TriggerSync(ctx context.Context) (r *QueueResponse, _ error) {
	return r, ht.ErrNotImplemented
}
