// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// ListStacks implements listStacks operation.
	//
	// GET /api/v1/stacks
	ListStacks(ctx context.Context) (*StacksResponse, error)
	// ReceiveGitWebhook implements receiveGitWebhook operation.
	//
	// POST /api/v1/webhooks/git
	ReceiveGitWebhook(ctx context.Context, req OptGitWebhookPayload, params ReceiveGitWebhookParams) (ReceiveGitWebhookRes, error)
	// TriggerSync implements triggerSync operation.
	//
	// POST /api/v1/sync
	TriggerSync(ctx context.Context) (*QueueResponse, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
