// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
)

// ReceiveGitWebhookParams is parameters of receiveGitWebhook operation.
type ReceiveGitWebhookParams struct {
	XSwarmDeploySecret OptString `json:",omitempty,omitzero"`
}

func unpackReceiveGitWebhookParams(packed middleware.Parameters) (params ReceiveGitWebhookParams) {
	{
		key := middleware.ParameterKey{
			Name: "X-Swarm-Deploy-Secret",
			In:   "header",
		}
		if v, ok := packed[key]; ok {
			params.XSwarmDeploySecret = v.(OptString)
		}
	}
	return params
}

func decodeReceiveGitWebhookParams(args [0]string, argsEscaped bool, r *http.Request) (params ReceiveGitWebhookParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: X-Swarm-Deploy-Secret.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "X-Swarm-Deploy-Secret",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotXSwarmDeploySecretVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotXSwarmDeploySecretVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.XSwarmDeploySecret.SetTo(paramsDotXSwarmDeploySecretVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "X-Swarm-Deploy-Secret",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}
