// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	ListStacksOperation        OperationName = "ListStacks"
	ReceiveGitWebhookOperation OperationName = "ReceiveGitWebhook"
	TriggerSyncOperation       OperationName = "TriggerSync"
)
