// Code generated by ogen, DO NOT EDIT.

package api

import (
	"time"

	"github.com/go-faster/jx"
)

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	Error string `json:"error"`
}

// GetError returns the value of Error.
func (s *ErrorResponse) GetError() string {
	return s.Error
}

// SetError sets the value of Error.
func (s *ErrorResponse) SetError(val string) {
	s.Error = val
}

func (*ErrorResponse) receiveGitWebhookRes() {}

// Ref: #/components/schemas/GitWebhookPayload
type GitWebhookPayload struct {
	Provider        OptString                      `json:"provider"`
	Repository      OptString                      `json:"repository"`
	Ref             OptString                      `json:"ref"`
	Commits         []GitWebhookPayloadCommitsItem `json:"commits"`
	AdditionalProps GitWebhookPayloadAdditional
}

// GetProvider returns the value of Provider.
func (s *GitWebhookPayload) GetProvider() OptString {
	return s.Provider
}

// GetRepository returns the value of Repository.
func (s *GitWebhookPayload) GetRepository() OptString {
	return s.Repository
}

// GetRef returns the value of Ref.
func (s *GitWebhookPayload) GetRef() OptString {
	return s.Ref
}

// GetCommits returns the value of Commits.
func (s *GitWebhookPayload) GetCommits() []GitWebhookPayloadCommitsItem {
	return s.Commits
}

// GetAdditionalProps returns the value of AdditionalProps.
func (s *GitWebhookPayload) GetAdditionalProps() GitWebhookPayloadAdditional {
	return s.AdditionalProps
}

// SetProvider sets the value of Provider.
func (s *GitWebhookPayload) SetProvider(val OptString) {
	s.Provider = val
}

// SetRepository sets the value of Repository.
func (s *GitWebhookPayload) SetRepository(val OptString) {
	s.Repository = val
}

// SetRef sets the value of Ref.
func (s *GitWebhookPayload) SetRef(val OptString) {
	s.Ref = val
}

// SetCommits sets the value of Commits.
func (s *GitWebhookPayload) SetCommits(val []GitWebhookPayloadCommitsItem) {
	s.Commits = val
}

// SetAdditionalProps sets the value of AdditionalProps.
func (s *GitWebhookPayload) SetAdditionalProps(val GitWebhookPayloadAdditional) {
	s.AdditionalProps = val
}

type GitWebhookPayloadAdditional map[string]jx.Raw

func (s *GitWebhookPayloadAdditional) init() GitWebhookPayloadAdditional {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

type GitWebhookPayloadCommitsItem map[string]jx.Raw

func (s *GitWebhookPayloadCommitsItem) init() GitWebhookPayloadCommitsItem {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptGitWebhookPayload returns new OptGitWebhookPayload with value set to v.
func NewOptGitWebhookPayload(v GitWebhookPayload) OptGitWebhookPayload {
	return OptGitWebhookPayload{
		Value: v,
		Set:   true,
	}
}

// OptGitWebhookPayload is optional GitWebhookPayload.
type OptGitWebhookPayload struct {
	Value GitWebhookPayload
	Set   bool
}

// IsSet returns true if OptGitWebhookPayload was set.
func (o OptGitWebhookPayload) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptGitWebhookPayload) Reset() {
	var v GitWebhookPayload
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptGitWebhookPayload) SetTo(v GitWebhookPayload) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptGitWebhookPayload) Get() (v GitWebhookPayload, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptGitWebhookPayload) Or(d GitWebhookPayload) GitWebhookPayload {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/QueueResponse
type QueueResponse struct {
	Queued bool `json:"queued"`
}

// GetQueued returns the value of Queued.
func (s *QueueResponse) GetQueued() bool {
	return s.Queued
}

// SetQueued sets the value of Queued.
func (s *QueueResponse) SetQueued(val bool) {
	s.Queued = val
}

func (*QueueResponse) receiveGitWebhookRes() {}

// Ref: #/components/schemas/ServiceView
type ServiceView struct {
	Name         string      `json:"name"`
	Image        OptString   `json:"image"`
	ImageVersion OptString   `json:"image_version"`
	LastStatus   OptString   `json:"last_status"`
	LastDeployAt OptDateTime `json:"last_deploy_at"`
}

// GetName returns the value of Name.
func (s *ServiceView) GetName() string {
	return s.Name
}

// GetImage returns the value of Image.
func (s *ServiceView) GetImage() OptString {
	return s.Image
}

// GetImageVersion returns the value of ImageVersion.
func (s *ServiceView) GetImageVersion() OptString {
	return s.ImageVersion
}

// GetLastStatus returns the value of LastStatus.
func (s *ServiceView) GetLastStatus() OptString {
	return s.LastStatus
}

// GetLastDeployAt returns the value of LastDeployAt.
func (s *ServiceView) GetLastDeployAt() OptDateTime {
	return s.LastDeployAt
}

// SetName sets the value of Name.
func (s *ServiceView) SetName(val string) {
	s.Name = val
}

// SetImage sets the value of Image.
func (s *ServiceView) SetImage(val OptString) {
	s.Image = val
}

// SetImageVersion sets the value of ImageVersion.
func (s *ServiceView) SetImageVersion(val OptString) {
	s.ImageVersion = val
}

// SetLastStatus sets the value of LastStatus.
func (s *ServiceView) SetLastStatus(val OptString) {
	s.LastStatus = val
}

// SetLastDeployAt sets the value of LastDeployAt.
func (s *ServiceView) SetLastDeployAt(val OptDateTime) {
	s.LastDeployAt = val
}

// Ref: #/components/schemas/StackView
type StackView struct {
	Name         string        `json:"name"`
	ComposeFile  string        `json:"compose_file"`
	LastStatus   string        `json:"last_status"`
	LastError    OptString     `json:"last_error"`
	LastCommit   OptString     `json:"last_commit"`
	LastDeployAt OptDateTime   `json:"last_deploy_at"`
	SourceDigest OptString     `json:"source_digest"`
	Services     []ServiceView `json:"services"`
}

// GetName returns the value of Name.
func (s *StackView) GetName() string {
	return s.Name
}

// GetComposeFile returns the value of ComposeFile.
func (s *StackView) GetComposeFile() string {
	return s.ComposeFile
}

// GetLastStatus returns the value of LastStatus.
func (s *StackView) GetLastStatus() string {
	return s.LastStatus
}

// GetLastError returns the value of LastError.
func (s *StackView) GetLastError() OptString {
	return s.LastError
}

// GetLastCommit returns the value of LastCommit.
func (s *StackView) GetLastCommit() OptString {
	return s.LastCommit
}

// GetLastDeployAt returns the value of LastDeployAt.
func (s *StackView) GetLastDeployAt() OptDateTime {
	return s.LastDeployAt
}

// GetSourceDigest returns the value of SourceDigest.
func (s *StackView) GetSourceDigest() OptString {
	return s.SourceDigest
}

// GetServices returns the value of Services.
func (s *StackView) GetServices() []ServiceView {
	return s.Services
}

// SetName sets the value of Name.
func (s *StackView) SetName(val string) {
	s.Name = val
}

// SetComposeFile sets the value of ComposeFile.
func (s *StackView) SetComposeFile(val string) {
	s.ComposeFile = val
}

// SetLastStatus sets the value of LastStatus.
func (s *StackView) SetLastStatus(val string) {
	s.LastStatus = val
}

// SetLastError sets the value of LastError.
func (s *StackView) SetLastError(val OptString) {
	s.LastError = val
}

// SetLastCommit sets the value of LastCommit.
func (s *StackView) SetLastCommit(val OptString) {
	s.LastCommit = val
}

// SetLastDeployAt sets the value of LastDeployAt.
func (s *StackView) SetLastDeployAt(val OptDateTime) {
	s.LastDeployAt = val
}

// SetSourceDigest sets the value of SourceDigest.
func (s *StackView) SetSourceDigest(val OptString) {
	s.SourceDigest = val
}

// SetServices sets the value of Services.
func (s *StackView) SetServices(val []ServiceView) {
	s.Services = val
}

// Ref: #/components/schemas/StacksResponse
type StacksResponse struct {
	Stacks []StackView `json:"stacks"`
	Sync   SyncInfo    `json:"sync"`
}

// GetStacks returns the value of Stacks.
func (s *StacksResponse) GetStacks() []StackView {
	return s.Stacks
}

// GetSync returns the value of Sync.
func (s *StacksResponse) GetSync() SyncInfo {
	return s.Sync
}

// SetStacks sets the value of Stacks.
func (s *StacksResponse) SetStacks(val []StackView) {
	s.Stacks = val
}

// SetSync sets the value of Sync.
func (s *StacksResponse) SetSync(val SyncInfo) {
	s.Sync = val
}

// Ref: #/components/schemas/SyncInfo
type SyncInfo map[string]string

func (s *SyncInfo) init() SyncInfo {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}
