// Code generated by MockGen. DO NOT EDIT.
// Source: subscriber.go
//
// Generated by this command:
//
//	mockgen -source=subscriber.go -destination=mocks.go -package=alertmanagement
//

// Package alertmanagement is a generated GoMock package.
package alertmanagement

import (
	context "context"
	reflect "reflect"

	model "github.com/swarm-deploy/swarm-deploy/internal/modules/alertmanagement/model"
	gomock "go.uber.org/mock/gomock"
)

// MockObserver is a mock of Observer interface.
type MockObserver struct {
	ctrl     *gomock.Controller
	recorder *MockObserverMockRecorder
	isgomock struct{}
}

// MockObserverMockRecorder is the mock recorder for MockObserver.
type MockObserverMockRecorder struct {
	mock *MockObserver
}

// NewMockObserver creates a new mock instance.
func NewMockObserver(ctrl *gomock.Controller) *MockObserver {
	mock := &MockObserver{ctrl: ctrl}
	mock.recorder = &MockObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObserver) EXPECT() *MockObserverMockRecorder {
	return m.recorder
}

// AlertOpened mocks base method.
func (m *MockObserver) AlertOpened(ctx context.Context, alert model.Alert) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AlertOpened", ctx, alert)
	ret0, _ := ret[0].(error)
	return ret0
}

// AlertOpened indicates an expected call of AlertOpened.
func (mr *MockObserverMockRecorder) AlertOpened(ctx, alert any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AlertOpened", reflect.TypeOf((*MockObserver)(nil).AlertOpened), ctx, alert)
}

// AlertResolved mocks base method.
func (m *MockObserver) AlertResolved(ctx context.Context, alert model.Alert) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AlertResolved", ctx, alert)
	ret0, _ := ret[0].(error)
	return ret0
}

// AlertResolved indicates an expected call of AlertResolved.
func (mr *MockObserverMockRecorder) AlertResolved(ctx, alert any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AlertResolved", reflect.TypeOf((*MockObserver)(nil).AlertResolved), ctx, alert)
}
