// Code generated by MockGen. DO NOT EDIT.
// Source: internal/modules/assistant/rag/types.go
//
// Generated by this command:
//
//	mockgen -source=internal/modules/assistant/rag/types.go -destination=internal/modules/assistant/rag/mocks.go -package=rag
//

// Package rag is a generated GoMock package.
package rag

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/swarm-deploy/swarm-deploy/internal/modules/resources/service/model"
	gomock "go.uber.org/mock/gomock"
)

// MockServiceStore is a mock of ServiceStore interface.
type MockServiceStore struct {
	ctrl     *gomock.Controller
	recorder *MockServiceStoreMockRecorder
	isgomock struct{}
}

// MockServiceStoreMockRecorder is the mock recorder for MockServiceStore.
type MockServiceStoreMockRecorder struct {
	mock *MockServiceStore
}

// NewMockServiceStore creates a new mock instance.
func NewMockServiceStore(ctrl *gomock.Controller) *MockServiceStore {
	mock := &MockServiceStore{ctrl: ctrl}
	mock.recorder = &MockServiceStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceStore) EXPECT() *MockServiceStoreMockRecorder {
	return m.recorder
}

// ReadAll mocks base method.
func (m *MockServiceStore) ReadAll(arg0 context.Context) ([]model.Info, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAll", arg0)
	ret0, _ := ret[0].([]model.Info)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAll indicates an expected call of ReadAll.
func (mr *MockServiceStoreMockRecorder) ReadAll(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAll", reflect.TypeOf((*MockServiceStore)(nil).ReadAll), arg0)
}

// MockEmbedder is a mock of Embedder interface.
type MockEmbedder struct {
	ctrl     *gomock.Controller
	recorder *MockEmbedderMockRecorder
	isgomock struct{}
}

// MockEmbedderMockRecorder is the mock recorder for MockEmbedder.
type MockEmbedderMockRecorder struct {
	mock *MockEmbedder
}

// NewMockEmbedder creates a new mock instance.
func NewMockEmbedder(ctrl *gomock.Controller) *MockEmbedder {
	mock := &MockEmbedder{ctrl: ctrl}
	mock.recorder = &MockEmbedderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmbedder) EXPECT() *MockEmbedderMockRecorder {
	return m.recorder
}

// Embed mocks base method.
func (m *MockEmbedder) Embed(ctx context.Context, arg1 string, inputs []string) ([][]float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Embed", ctx, arg1, inputs)
	ret0, _ := ret[0].([][]float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Embed indicates an expected call of Embed.
func (mr *MockEmbedderMockRecorder) Embed(ctx, arg1, inputs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Embed", reflect.TypeOf((*MockEmbedder)(nil).Embed), ctx, arg1, inputs)
}

// MockObserver is a mock of Observer interface.
type MockObserver struct {
	ctrl     *gomock.Controller
	recorder *MockObserverMockRecorder
	isgomock struct{}
}

// MockObserverMockRecorder is the mock recorder for MockObserver.
type MockObserverMockRecorder struct {
	mock *MockObserver
}

// NewMockObserver creates a new mock instance.
func NewMockObserver(ctrl *gomock.Controller) *MockObserver {
	mock := &MockObserver{ctrl: ctrl}
	mock.recorder = &MockObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObserver) EXPECT() *MockObserverMockRecorder {
	return m.recorder
}

// RecordIndexRebuild mocks base method.
func (m *MockObserver) RecordIndexRebuild(status string, size int, duration time.Duration, updatedAt time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordIndexRebuild", status, size, duration, updatedAt)
}

// RecordIndexRebuild indicates an expected call of RecordIndexRebuild.
func (mr *MockObserverMockRecorder) RecordIndexRebuild(status, size, duration, updatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordIndexRebuild", reflect.TypeOf((*MockObserver)(nil).RecordIndexRebuild), status, size, duration, updatedAt)
}

// RecordRetrieveFallback mocks base method.
func (m *MockObserver) RecordRetrieveFallback(reason string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordRetrieveFallback", reason)
}

// RecordRetrieveFallback indicates an expected call of RecordRetrieveFallback.
func (mr *MockObserverMockRecorder) RecordRetrieveFallback(reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordRetrieveFallback", reflect.TypeOf((*MockObserver)(nil).RecordRetrieveFallback), reason)
}
