// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/swarm-deploy/swarm-deploy/internal/githosting (interfaces: Provider)
//
// Generated by this command:
//
//	mockgen -destination=/tmp/mock_githosting_provider.go -package=githosting github.com/swarm-deploy/swarm-deploy/internal/githosting Provider
//

package githosting

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// GetLatestRelease mocks base method.
func (m *MockProvider) GetLatestRelease(ctx context.Context, repo RepositoryReference) (*Release, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestRelease", ctx, repo)
	ret0, _ := ret[0].(*Release)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestRelease indicates an expected call of GetLatestRelease.
func (mr *MockProviderMockRecorder) GetLatestRelease(ctx, repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestRelease", reflect.TypeOf((*MockProvider)(nil).GetLatestRelease), ctx, repo)
}
