// Code generated by MockGen. DO NOT EDIT.
// Source: dispatcher.go
//
// Generated by this command:
//
//	mockgen -source=dispatcher.go -destination=mocks.go -package=dispatcher
//

// Package dispatcher is a generated GoMock package.
package dispatcher

import (
	context "context"
	reflect "reflect"

	events "github.com/swarm-deploy/swarm-deploy/internal/modules/event/events"
	outbox "github.com/swarm-deploy/swarm-deploy/internal/modules/event/outbox"
	gomock "go.uber.org/mock/gomock"
)

// MockDispatcher is a mock of Dispatcher interface.
type MockDispatcher struct {
	ctrl     *gomock.Controller
	recorder *MockDispatcherMockRecorder
	isgomock struct{}
}

// MockDispatcherMockRecorder is the mock recorder for MockDispatcher.
type MockDispatcherMockRecorder struct {
	mock *MockDispatcher
}

// NewMockDispatcher creates a new mock instance.
func NewMockDispatcher(ctrl *gomock.Controller) *MockDispatcher {
	mock := &MockDispatcher{ctrl: ctrl}
	mock.recorder = &MockDispatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDispatcher) EXPECT() *MockDispatcherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockDispatcher) Publish(ctx context.Context, event events.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockDispatcherMockRecorder) Publish(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockDispatcher)(nil).Publish), ctx, event)
}

// Subscribe mocks base method.
func (m *MockDispatcher) Subscribe(eventType events.TypeName, id string, subscriber outbox.Subscriber) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", eventType, id, subscriber)
	ret0, _ := ret[0].(error)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockDispatcherMockRecorder) Subscribe(eventType, id, subscriber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockDispatcher)(nil).Subscribe), eventType, id, subscriber)
}
