package assistant

import (
	"context"
	"errors"
	"log/slog"
	"strings"
	"sync"
	"time"

	"github.com/artarts36/swarm-deploy/internal/assistant/guard"
	"github.com/google/uuid"
)

const (
	defaultPollAfterMS   = 1000
	defaultWaitTimeoutMS = 12000
	maxWaitTimeoutMS     = 30000
	maxConversationTurns = 24
	runRetention         = 30 * time.Minute
	runExecutionTimeout  = 2 * time.Minute
)

// Service provides assistant chat workflow with start/poll semantics.
type Service struct {
	config Config
	graph  *graph

	runsMu sync.RWMutex
	runs   map[string]*chatRun

	conversationMu sync.RWMutex
	conversation   map[string][]conversationTurn
}

// NewService creates assistant service with OpenAI-compatible clients.
func NewService(config Config, store ServiceStore, tools ToolExecutor) (*Service, error) {
	modelClient := newOpenAIClient(config.BaseURL, config.APIToken, config.OrganizationID)

	return newService(config, store, tools, modelClient)
}

func newService(
	config Config,
	store ServiceStore,
	tools ToolExecutor,
	modelClient *openAIClient,
) (*Service, error) {
	if store == nil {
		return nil, errors.New("assistant service store is nil")
	}
	if tools == nil {
		return nil, errors.New("assistant tools executor is nil")
	}
	if modelClient == nil {
		return nil, errors.New("assistant model client is nil")
	}

	retriever := newRetriever(store, modelClient, strings.TrimSpace(config.ModelName))
	allowedTools := normalizeAllowedTools(config.AllowedTools)

	return &Service{
		config: config,
		graph: newGraph(
			config,
			guard.NewInjectionChecker(),
			retriever,
			modelClient,
			tools,
			allowedTools,
		),
		runs:         map[string]*chatRun{},
		conversation: map[string][]conversationTurn{},
	}, nil
}

// Chat handles new assistant requests and polling requests.
func (s *Service) Chat(ctx context.Context, request ChatRequest) ChatResponse {
	conversationID := strings.TrimSpace(request.ConversationID)
	requestID := strings.TrimSpace(request.RequestID)
	message := strings.TrimSpace(request.Message)

	if !s.config.Enabled {
		return ChatResponse{
			Status:         StatusDisabled,
			ConversationID: conversationID,
			RequestID:      requestID,
			ErrorMessage:   "assistant is disabled in configuration",
		}
	}

	waitTimeout := sanitizeWaitTimeout(request.WaitTimeoutMS)

	if requestID != "" && message == "" {
		run := s.getRun(requestID)
		if run == nil {
			return ChatResponse{
				Status:         StatusFailed,
				ConversationID: conversationID,
				RequestID:      requestID,
				ErrorMessage:   "unknown request_id",
			}
		}

		return s.awaitRun(ctx, run, waitTimeout)
	}

	if message == "" {
		return ChatResponse{
			Status:         StatusFailed,
			ConversationID: conversationID,
			RequestID:      requestID,
			ErrorMessage:   "message is required for new assistant request",
		}
	}

	if conversationID == "" {
		conversationID = uuid.NewString()
	}
	if requestID == "" {
		requestID = uuid.NewString()
	}

	run, created := s.getOrCreateRun(requestID, conversationID)
	if created {
		go s.runAssistant(conversationID, message, run)
	}

	return s.awaitRun(ctx, run, waitTimeout)
}

func (s *Service) runAssistant(conversationID, message string, run *chatRun) {
	ctx, cancel := context.WithTimeout(context.Background(), runExecutionTimeout)
	defer cancel()

	history := s.getConversation(conversationID)
	answer, _, err := s.graph.run(ctx, history, message)
	if err != nil {
		if errors.Is(err, errPromptInjection) {
			run.finish(
				StatusRejected,
				"",
				"Request was rejected by prompt injection protection. Rephrase your debugging question.",
			)
			return
		}

		slog.ErrorContext(
			ctx,
			"[assistant] failed to generate response",
			slog.String("conversation_id", conversationID),
			slog.String("request_id", run.requestID),
			slog.Any("err", err),
		)
		run.finish(StatusFailed, "", "Failed to generate assistant response")
		return
	}

	answer = strings.TrimSpace(answer)
	if answer == "" {
		answer = "No answer generated by model."
	}

	s.appendConversation(conversationID, conversationTurn{
		role:    "user",
		content: message,
	}, conversationTurn{
		role:    "assistant",
		content: answer,
	})

	run.finish(StatusCompleted, answer, "")
}

func (s *Service) awaitRun(ctx context.Context, run *chatRun, waitTimeout time.Duration) ChatResponse {
	select {
	case <-run.done:
		return run.snapshot()
	default:
	}

	timer := time.NewTimer(waitTimeout)
	defer timer.Stop()

	select {
	case <-run.done:
		return run.snapshot()
	case <-timer.C:
		return ChatResponse{
			Status:         StatusInProgress,
			ConversationID: run.conversationID,
			RequestID:      run.requestID,
			PollAfterMS:    defaultPollAfterMS,
		}
	case <-ctx.Done():
		return ChatResponse{
			Status:         StatusInProgress,
			ConversationID: run.conversationID,
			RequestID:      run.requestID,
			PollAfterMS:    defaultPollAfterMS,
		}
	}
}

func (s *Service) getRun(requestID string) *chatRun {
	s.runsMu.RLock()
	defer s.runsMu.RUnlock()

	return s.runs[requestID]
}

func (s *Service) getOrCreateRun(requestID, conversationID string) (*chatRun, bool) {
	s.runsMu.Lock()
	defer s.runsMu.Unlock()

	s.pruneRunsLocked()

	if existing := s.runs[requestID]; existing != nil {
		return existing, false
	}

	run := newChatRun(requestID, conversationID)
	s.runs[requestID] = run
	return run, true
}

func (s *Service) pruneRunsLocked() {
	cutoff := time.Now().Add(-runRetention)
	for requestID, run := range s.runs {
		if !run.isFinished() {
			continue
		}
		if run.finishedAt.Before(cutoff) {
			delete(s.runs, requestID)
		}
	}
}

func (s *Service) getConversation(conversationID string) []conversationTurn {
	s.conversationMu.RLock()
	defer s.conversationMu.RUnlock()

	turns := s.conversation[conversationID]
	out := make([]conversationTurn, len(turns))
	copy(out, turns)
	return out
}

func (s *Service) appendConversation(conversationID string, turns ...conversationTurn) {
	s.conversationMu.Lock()
	defer s.conversationMu.Unlock()

	current := append(s.conversation[conversationID], turns...)
	if len(current) > maxConversationTurns {
		current = current[len(current)-maxConversationTurns:]
	}
	s.conversation[conversationID] = current
}

func sanitizeWaitTimeout(timeoutMS int) time.Duration {
	if timeoutMS <= 0 {
		timeoutMS = defaultWaitTimeoutMS
	}
	if timeoutMS > maxWaitTimeoutMS {
		timeoutMS = maxWaitTimeoutMS
	}

	return time.Duration(timeoutMS) * time.Millisecond
}

func normalizeAllowedTools(allowedTools []string) map[string]struct{} {
	normalized := map[string]struct{}{}
	for _, toolName := range allowedTools {
		toolName = strings.TrimSpace(toolName)
		if toolName == "" {
			continue
		}
		normalized[toolName] = struct{}{}
	}

	return normalized
}

type chatRun struct {
	requestID      string
	conversationID string

	done chan struct{}

	mu         sync.RWMutex
	status     Status
	answer     string
	error      string
	finishedAt time.Time
}

func newChatRun(requestID, conversationID string) *chatRun {
	return &chatRun{
		requestID:      requestID,
		conversationID: conversationID,
		done:           make(chan struct{}),
		status:         StatusInProgress,
	}
}

func (r *chatRun) isFinished() bool {
	r.mu.RLock()
	defer r.mu.RUnlock()

	return r.status != StatusInProgress
}

func (r *chatRun) finish(status Status, answer string, errorMessage string) {
	r.mu.Lock()
	if r.status != StatusInProgress {
		r.mu.Unlock()
		return
	}

	r.status = status
	r.answer = strings.TrimSpace(answer)
	r.error = strings.TrimSpace(errorMessage)
	r.finishedAt = time.Now()
	r.mu.Unlock()

	close(r.done)
}

func (r *chatRun) snapshot() ChatResponse {
	r.mu.RLock()
	defer r.mu.RUnlock()

	return ChatResponse{
		Status:         r.status,
		ConversationID: r.conversationID,
		RequestID:      r.requestID,
		Answer:         r.answer,
		ErrorMessage:   r.error,
	}
}
