// Code generated by MockGen. DO NOT EDIT.
// Source: dispatcher.go
//
// Generated by this command:
//
//	mockgen -source=dispatcher.go -destination=mocks.go -package=dispatcher
//

// Package dispatcher is a generated GoMock package.
package dispatcher

import (
	context "context"
	reflect "reflect"

	events "github.com/swarm-deploy/swarm-deploy/internal/event/events"
	gomock "go.uber.org/mock/gomock"
)

// MockDispatcher is a mock of Dispatcher interface.
type MockDispatcher struct {
	ctrl     *gomock.Controller
	recorder *MockDispatcherMockRecorder
	isgomock struct{}
}

// MockDispatcherMockRecorder is the mock recorder for MockDispatcher.
type MockDispatcherMockRecorder struct {
	mock *MockDispatcher
}

// NewMockDispatcher creates a new mock instance.
func NewMockDispatcher(ctrl *gomock.Controller) *MockDispatcher {
	mock := &MockDispatcher{ctrl: ctrl}
	mock.recorder = &MockDispatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDispatcher) EXPECT() *MockDispatcherMockRecorder {
	return m.recorder
}

// Dispatch mocks base method.
func (m *MockDispatcher) Dispatch(ctx context.Context, event events.Event) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Dispatch", ctx, event)
}

// Dispatch indicates an expected call of Dispatch.
func (mr *MockDispatcherMockRecorder) Dispatch(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dispatch", reflect.TypeOf((*MockDispatcher)(nil).Dispatch), ctx, event)
}

// Shutdown mocks base method.
func (m *MockDispatcher) Shutdown(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockDispatcherMockRecorder) Shutdown(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockDispatcher)(nil).Shutdown), ctx)
}

// Subscribe mocks base method.
func (m *MockDispatcher) Subscribe(eventType events.Type, subscriber Subscriber) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Subscribe", eventType, subscriber)
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockDispatcherMockRecorder) Subscribe(eventType, subscriber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockDispatcher)(nil).Subscribe), eventType, subscriber)
}
