// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mock_controller.go -package=cloudsecrets
//

// Package cloudsecrets is a generated GoMock package.
package cloudsecrets

import (
	context "context"
	reflect "reflect"

	grpcapi "github.com/swarm-deploy/cloud-secrets/pkg/grpc-api"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockController is a mock of Controller interface.
type MockController struct {
	ctrl     *gomock.Controller
	recorder *MockControllerMockRecorder
	isgomock struct{}
}

// MockControllerMockRecorder is the mock recorder for MockController.
type MockControllerMockRecorder struct {
	mock *MockController
}

// NewMockController creates a new mock instance.
func NewMockController(ctrl *gomock.Controller) *MockController {
	mock := &MockController{ctrl: ctrl}
	mock.recorder = &MockControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockController) EXPECT() *MockControllerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockController) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockControllerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockController)(nil).Close))
}

// GetInfo mocks base method.
func (m *MockController) GetInfo(ctx context.Context) (Info, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInfo", ctx)
	ret0, _ := ret[0].(Info)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInfo indicates an expected call of GetInfo.
func (mr *MockControllerMockRecorder) GetInfo(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInfo", reflect.TypeOf((*MockController)(nil).GetInfo), ctx)
}

// Sync mocks base method.
func (m *MockController) Sync(ctx context.Context) (SyncResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync", ctx)
	ret0, _ := ret[0].(SyncResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sync indicates an expected call of Sync.
func (mr *MockControllerMockRecorder) Sync(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockController)(nil).Sync), ctx)
}

// MockcontrollerAPI is a mock of controllerAPI interface.
type MockcontrollerAPI struct {
	ctrl     *gomock.Controller
	recorder *MockcontrollerAPIMockRecorder
	isgomock struct{}
}

// MockcontrollerAPIMockRecorder is the mock recorder for MockcontrollerAPI.
type MockcontrollerAPIMockRecorder struct {
	mock *MockcontrollerAPI
}

// NewMockcontrollerAPI creates a new mock instance.
func NewMockcontrollerAPI(ctrl *gomock.Controller) *MockcontrollerAPI {
	mock := &MockcontrollerAPI{ctrl: ctrl}
	mock.recorder = &MockcontrollerAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcontrollerAPI) EXPECT() *MockcontrollerAPIMockRecorder {
	return m.recorder
}

// GetInfo mocks base method.
func (m *MockcontrollerAPI) GetInfo(ctx context.Context, in *grpcapi.GetInfoRequest, opts ...grpc.CallOption) (*grpcapi.GetInfoResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetInfo", varargs...)
	ret0, _ := ret[0].(*grpcapi.GetInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInfo indicates an expected call of GetInfo.
func (mr *MockcontrollerAPIMockRecorder) GetInfo(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInfo", reflect.TypeOf((*MockcontrollerAPI)(nil).GetInfo), varargs...)
}

// Sync mocks base method.
func (m *MockcontrollerAPI) Sync(ctx context.Context, in *grpcapi.SyncRequest, opts ...grpc.CallOption) (*grpcapi.SyncResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Sync", varargs...)
	ret0, _ := ret[0].(*grpcapi.SyncResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sync indicates an expected call of Sync.
func (mr *MockcontrollerAPIMockRecorder) Sync(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockcontrollerAPI)(nil).Sync), varargs...)
}
