// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: swarm_deploy/cloud_secrets/controller.proto

package cloudsecretspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_swarm_deploy_cloud_secrets_controller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_deploy_cloud_secrets_controller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_swarm_deploy_cloud_secrets_controller_proto_rawDescGZIP(), []int{0}
}

type GetInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Provider      *Provider              `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	LastSyncAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_sync_at,json=lastSyncAt,proto3" json:"last_sync_at,omitempty"`
	NextSyncAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=next_sync_at,json=nextSyncAt,proto3" json:"next_sync_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	mi := &file_swarm_deploy_cloud_secrets_controller_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_deploy_cloud_secrets_controller_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_swarm_deploy_cloud_secrets_controller_proto_rawDescGZIP(), []int{1}
}

func (x *GetInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetInfoResponse) GetProvider() *Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *GetInfoResponse) GetLastSyncAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSyncAt
	}
	return nil
}

func (x *GetInfoResponse) GetNextSyncAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextSyncAt
	}
	return nil
}

type Provider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Links         *Links                 `protobuf:"bytes,2,opt,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Provider) Reset() {
	*x = Provider{}
	mi := &file_swarm_deploy_cloud_secrets_controller_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provider) ProtoMessage() {}

func (x *Provider) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_deploy_cloud_secrets_controller_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provider.ProtoReflect.Descriptor instead.
func (*Provider) Descriptor() ([]byte, []int) {
	return file_swarm_deploy_cloud_secrets_controller_proto_rawDescGZIP(), []int{2}
}

func (x *Provider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Provider) GetLinks() *Links {
	if x != nil {
		return x.Links
	}
	return nil
}

type Links struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Doc           string                 `protobuf:"bytes,1,opt,name=doc,proto3" json:"doc,omitempty"`
	Manager       string                 `protobuf:"bytes,2,opt,name=manager,proto3" json:"manager,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Links) Reset() {
	*x = Links{}
	mi := &file_swarm_deploy_cloud_secrets_controller_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Links) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Links) ProtoMessage() {}

func (x *Links) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_deploy_cloud_secrets_controller_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Links.ProtoReflect.Descriptor instead.
func (*Links) Descriptor() ([]byte, []int) {
	return file_swarm_deploy_cloud_secrets_controller_proto_rawDescGZIP(), []int{3}
}

func (x *Links) GetDoc() string {
	if x != nil {
		return x.Doc
	}
	return ""
}

func (x *Links) GetManager() string {
	if x != nil {
		return x.Manager
	}
	return ""
}

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_swarm_deploy_cloud_secrets_controller_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_deploy_cloud_secrets_controller_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_swarm_deploy_cloud_secrets_controller_proto_rawDescGZIP(), []int{4}
}

type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Created       uint32                 `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Updated       uint32                 `protobuf:"varint,2,opt,name=updated,proto3" json:"updated,omitempty"`
	Removed       uint32                 `protobuf:"varint,3,opt,name=removed,proto3" json:"removed,omitempty"`
	Unchanged     uint32                 `protobuf:"varint,4,opt,name=unchanged,proto3" json:"unchanged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_swarm_deploy_cloud_secrets_controller_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_deploy_cloud_secrets_controller_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_swarm_deploy_cloud_secrets_controller_proto_rawDescGZIP(), []int{5}
}

func (x *SyncResponse) GetCreated() uint32 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *SyncResponse) GetUpdated() uint32 {
	if x != nil {
		return x.Updated
	}
	return 0
}

func (x *SyncResponse) GetRemoved() uint32 {
	if x != nil {
		return x.Removed
	}
	return 0
}

func (x *SyncResponse) GetUnchanged() uint32 {
	if x != nil {
		return x.Unchanged
	}
	return 0
}

var File_swarm_deploy_cloud_secrets_controller_proto protoreflect.FileDescriptor

const file_swarm_deploy_cloud_secrets_controller_proto_rawDesc = "" +
	"\n" +
	"+swarm_deploy/cloud_secrets/controller.proto\x12\x1aswarm_deploy.cloud_secrets\x1a\x1fgoogle/protobuf/timestamp.proto\"\x10\n" +
	"\x0eGetInfoRequest\"\xe9\x01\n" +
	"\x0fGetInfoResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12@\n" +
	"\bprovider\x18\x02 \x01(\v2$.swarm_deploy.cloud_secrets.ProviderR\bprovider\x12<\n" +
	"\flast_sync_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSyncAt\x12<\n" +
	"\fnext_sync_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"nextSyncAt\"W\n" +
	"\bProvider\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\x05links\x18\x02 \x01(\v2!.swarm_deploy.cloud_secrets.LinksR\x05links\"3\n" +
	"\x05Links\x12\x10\n" +
	"\x03doc\x18\x01 \x01(\tR\x03doc\x12\x18\n" +
	"\amanager\x18\x02 \x01(\tR\amanager\"\r\n" +
	"\vSyncRequest\"z\n" +
	"\fSyncResponse\x12\x18\n" +
	"\acreated\x18\x01 \x01(\rR\acreated\x12\x18\n" +
	"\aupdated\x18\x02 \x01(\rR\aupdated\x12\x18\n" +
	"\aremoved\x18\x03 \x01(\rR\aremoved\x12\x1c\n" +
	"\tunchanged\x18\x04 \x01(\rR\tunchanged2\xcb\x01\n" +
	"\n" +
	"Controller\x12b\n" +
	"\aGetInfo\x12*.swarm_deploy.cloud_secrets.GetInfoRequest\x1a+.swarm_deploy.cloud_secrets.GetInfoResponse\x12Y\n" +
	"\x04Sync\x12'.swarm_deploy.cloud_secrets.SyncRequest\x1a(.swarm_deploy.cloud_secrets.SyncResponseB<Z:github.com/swarm-deploy/cloud-secrets/pkg/grpc-api;grpcapib\x06proto3"

var (
	file_swarm_deploy_cloud_secrets_controller_proto_rawDescOnce sync.Once
	file_swarm_deploy_cloud_secrets_controller_proto_rawDescData []byte
)

func file_swarm_deploy_cloud_secrets_controller_proto_rawDescGZIP() []byte {
	file_swarm_deploy_cloud_secrets_controller_proto_rawDescOnce.Do(func() {
		file_swarm_deploy_cloud_secrets_controller_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swarm_deploy_cloud_secrets_controller_proto_rawDesc), len(file_swarm_deploy_cloud_secrets_controller_proto_rawDesc)))
	})
	return file_swarm_deploy_cloud_secrets_controller_proto_rawDescData
}

var file_swarm_deploy_cloud_secrets_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_swarm_deploy_cloud_secrets_controller_proto_goTypes = []any{
	(*GetInfoRequest)(nil),        // 0: swarm_deploy.cloud_secrets.GetInfoRequest
	(*GetInfoResponse)(nil),       // 1: swarm_deploy.cloud_secrets.GetInfoResponse
	(*Provider)(nil),              // 2: swarm_deploy.cloud_secrets.Provider
	(*Links)(nil),                 // 3: swarm_deploy.cloud_secrets.Links
	(*SyncRequest)(nil),           // 4: swarm_deploy.cloud_secrets.SyncRequest
	(*SyncResponse)(nil),          // 5: swarm_deploy.cloud_secrets.SyncResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_swarm_deploy_cloud_secrets_controller_proto_depIdxs = []int32{
	2, // 0: swarm_deploy.cloud_secrets.GetInfoResponse.provider:type_name -> swarm_deploy.cloud_secrets.Provider
	6, // 1: swarm_deploy.cloud_secrets.GetInfoResponse.last_sync_at:type_name -> google.protobuf.Timestamp
	6, // 2: swarm_deploy.cloud_secrets.GetInfoResponse.next_sync_at:type_name -> google.protobuf.Timestamp
	3, // 3: swarm_deploy.cloud_secrets.Provider.links:type_name -> swarm_deploy.cloud_secrets.Links
	0, // 4: swarm_deploy.cloud_secrets.Controller.GetInfo:input_type -> swarm_deploy.cloud_secrets.GetInfoRequest
	4, // 5: swarm_deploy.cloud_secrets.Controller.Sync:input_type -> swarm_deploy.cloud_secrets.SyncRequest
	1, // 6: swarm_deploy.cloud_secrets.Controller.GetInfo:output_type -> swarm_deploy.cloud_secrets.GetInfoResponse
	5, // 7: swarm_deploy.cloud_secrets.Controller.Sync:output_type -> swarm_deploy.cloud_secrets.SyncResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_swarm_deploy_cloud_secrets_controller_proto_init() }
func file_swarm_deploy_cloud_secrets_controller_proto_init() {
	if File_swarm_deploy_cloud_secrets_controller_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swarm_deploy_cloud_secrets_controller_proto_rawDesc), len(file_swarm_deploy_cloud_secrets_controller_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_swarm_deploy_cloud_secrets_controller_proto_goTypes,
		DependencyIndexes: file_swarm_deploy_cloud_secrets_controller_proto_depIdxs,
		MessageInfos:      file_swarm_deploy_cloud_secrets_controller_proto_msgTypes,
	}.Build()
	File_swarm_deploy_cloud_secrets_controller_proto = out.File
	file_swarm_deploy_cloud_secrets_controller_proto_goTypes = nil
	file_swarm_deploy_cloud_secrets_controller_proto_depIdxs = nil
}
