// Code generated by MockGen. DO NOT EDIT.
// Source: internal/modules/assistant/types.go
//
// Generated by this command:
//
//	mockgen -source=internal/modules/assistant/types.go -destination=internal/modules/assistant/mocks.go -package=assistant
//

// Package assistant is a generated GoMock package.
package assistant

import (
	context "context"
	reflect "reflect"

	routing "github.com/swarm-deploy/swarm-deploy/internal/modules/assistant/tools/routing"
	model "github.com/swarm-deploy/swarm-deploy/internal/modules/resources/service/model"
	gomock "go.uber.org/mock/gomock"
)

// MockServiceStore is a mock of ServiceStore interface.
type MockServiceStore struct {
	ctrl     *gomock.Controller
	recorder *MockServiceStoreMockRecorder
	isgomock struct{}
}

// MockServiceStoreMockRecorder is the mock recorder for MockServiceStore.
type MockServiceStoreMockRecorder struct {
	mock *MockServiceStore
}

// NewMockServiceStore creates a new mock instance.
func NewMockServiceStore(ctrl *gomock.Controller) *MockServiceStore {
	mock := &MockServiceStore{ctrl: ctrl}
	mock.recorder = &MockServiceStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceStore) EXPECT() *MockServiceStoreMockRecorder {
	return m.recorder
}

// ReadAll mocks base method.
func (m *MockServiceStore) ReadAll(ctx context.Context) ([]model.Info, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAll", ctx)
	ret0, _ := ret[0].([]model.Info)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAll indicates an expected call of ReadAll.
func (mr *MockServiceStoreMockRecorder) ReadAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAll", reflect.TypeOf((*MockServiceStore)(nil).ReadAll), ctx)
}

// MockToolExecutor is a mock of ToolExecutor interface.
type MockToolExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockToolExecutorMockRecorder
	isgomock struct{}
}

// MockToolExecutorMockRecorder is the mock recorder for MockToolExecutor.
type MockToolExecutorMockRecorder struct {
	mock *MockToolExecutor
}

// NewMockToolExecutor creates a new mock instance.
func NewMockToolExecutor(ctrl *gomock.Controller) *MockToolExecutor {
	mock := &MockToolExecutor{ctrl: ctrl}
	mock.recorder = &MockToolExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockToolExecutor) EXPECT() *MockToolExecutorMockRecorder {
	return m.recorder
}

// Definitions mocks base method.
func (m *MockToolExecutor) Definitions() []routing.ToolDefinition {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Definitions")
	ret0, _ := ret[0].([]routing.ToolDefinition)
	return ret0
}

// Definitions indicates an expected call of Definitions.
func (mr *MockToolExecutorMockRecorder) Definitions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Definitions", reflect.TypeOf((*MockToolExecutor)(nil).Definitions))
}

// Execute mocks base method.
func (m *MockToolExecutor) Execute(ctx context.Context, req routing.Request) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockToolExecutorMockRecorder) Execute(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockToolExecutor)(nil).Execute), ctx, req)
}
