// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks.go -package=swarm
//

// Package swarm is a generated GoMock package.
package swarm

import (
	context "context"
	reflect "reflect"

	swarm "github.com/docker/docker/api/types/swarm"
	gomock "go.uber.org/mock/gomock"
)

// MockServiceManager is a mock of ServiceManager interface.
type MockServiceManager struct {
	ctrl     *gomock.Controller
	recorder *MockServiceManagerMockRecorder
	isgomock struct{}
}

// MockServiceManagerMockRecorder is the mock recorder for MockServiceManager.
type MockServiceManagerMockRecorder struct {
	mock *MockServiceManager
}

// NewMockServiceManager creates a new mock instance.
func NewMockServiceManager(ctrl *gomock.Controller) *MockServiceManager {
	mock := &MockServiceManager{ctrl: ctrl}
	mock.recorder = &MockServiceManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceManager) EXPECT() *MockServiceManagerMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockServiceManager) Get(ctx context.Context, serviceRef ServiceReference) (Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, serviceRef)
	ret0, _ := ret[0].(Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockServiceManagerMockRecorder) Get(ctx, serviceRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockServiceManager)(nil).Get), ctx, serviceRef)
}

// GetReplicas mocks base method.
func (m *MockServiceManager) GetReplicas(ctx context.Context, serviceRef ServiceReference) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReplicas", ctx, serviceRef)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReplicas indicates an expected call of GetReplicas.
func (mr *MockServiceManagerMockRecorder) GetReplicas(ctx, serviceRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReplicas", reflect.TypeOf((*MockServiceManager)(nil).GetReplicas), ctx, serviceRef)
}

// GetStatus mocks base method.
func (m *MockServiceManager) GetStatus(ctx context.Context, serviceRef ServiceReference) (ServiceStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus", ctx, serviceRef)
	ret0, _ := ret[0].(ServiceStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockServiceManagerMockRecorder) GetStatus(ctx, serviceRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockServiceManager)(nil).GetStatus), ctx, serviceRef)
}

// Labels mocks base method.
func (m *MockServiceManager) Labels(ctx context.Context, serviceRef ServiceReference) (ServiceLabels, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Labels", ctx, serviceRef)
	ret0, _ := ret[0].(ServiceLabels)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Labels indicates an expected call of Labels.
func (mr *MockServiceManagerMockRecorder) Labels(ctx, serviceRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Labels", reflect.TypeOf((*MockServiceManager)(nil).Labels), ctx, serviceRef)
}

// ListStackServices mocks base method.
func (m *MockServiceManager) ListStackServices(ctx context.Context, stackName string) ([]StackService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStackServices", ctx, stackName)
	ret0, _ := ret[0].([]StackService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStackServices indicates an expected call of ListStackServices.
func (mr *MockServiceManagerMockRecorder) ListStackServices(ctx, stackName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStackServices", reflect.TypeOf((*MockServiceManager)(nil).ListStackServices), ctx, stackName)
}

// ListTasks mocks base method.
func (m *MockServiceManager) ListTasks(ctx context.Context, serviceRef ServiceReference) ([]ServiceTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTasks", ctx, serviceRef)
	ret0, _ := ret[0].([]ServiceTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTasks indicates an expected call of ListTasks.
func (mr *MockServiceManagerMockRecorder) ListTasks(ctx, serviceRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTasks", reflect.TypeOf((*MockServiceManager)(nil).ListTasks), ctx, serviceRef)
}

// Logs mocks base method.
func (m *MockServiceManager) Logs(ctx context.Context, serviceRef ServiceReference, options ServiceLogsOptions) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logs", ctx, serviceRef, options)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Logs indicates an expected call of Logs.
func (mr *MockServiceManagerMockRecorder) Logs(ctx, serviceRef, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logs", reflect.TypeOf((*MockServiceManager)(nil).Logs), ctx, serviceRef, options)
}

// Remove mocks base method.
func (m *MockServiceManager) Remove(ctx context.Context, serviceIDOrName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, serviceIDOrName)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockServiceManagerMockRecorder) Remove(ctx, serviceIDOrName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockServiceManager)(nil).Remove), ctx, serviceIDOrName)
}

// Restart mocks base method.
func (m *MockServiceManager) Restart(ctx context.Context, serviceRef ServiceReference) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restart", ctx, serviceRef)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Restart indicates an expected call of Restart.
func (mr *MockServiceManagerMockRecorder) Restart(ctx, serviceRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restart", reflect.TypeOf((*MockServiceManager)(nil).Restart), ctx, serviceRef)
}

// Scale mocks base method.
func (m *MockServiceManager) Scale(ctx context.Context, serviceRef ServiceReference, replicas uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scale", ctx, serviceRef, replicas)
	ret0, _ := ret[0].(error)
	return ret0
}

// Scale indicates an expected call of Scale.
func (mr *MockServiceManagerMockRecorder) Scale(ctx, serviceRef, replicas any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scale", reflect.TypeOf((*MockServiceManager)(nil).Scale), ctx, serviceRef, replicas)
}

// MockSecretManager is a mock of SecretManager interface.
type MockSecretManager struct {
	ctrl     *gomock.Controller
	recorder *MockSecretManagerMockRecorder
	isgomock struct{}
}

// MockSecretManagerMockRecorder is the mock recorder for MockSecretManager.
type MockSecretManagerMockRecorder struct {
	mock *MockSecretManager
}

// NewMockSecretManager creates a new mock instance.
func NewMockSecretManager(ctrl *gomock.Controller) *MockSecretManager {
	mock := &MockSecretManager{ctrl: ctrl}
	mock.recorder = &MockSecretManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretManager) EXPECT() *MockSecretManagerMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockSecretManager) List(ctx context.Context) ([]Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSecretManagerMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSecretManager)(nil).List), ctx)
}

// ResolveReference mocks base method.
func (m *MockSecretManager) ResolveReference(ctx context.Context, source, target string) (*swarm.SecretReference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveReference", ctx, source, target)
	ret0, _ := ret[0].(*swarm.SecretReference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveReference indicates an expected call of ResolveReference.
func (mr *MockSecretManagerMockRecorder) ResolveReference(ctx, source, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveReference", reflect.TypeOf((*MockSecretManager)(nil).ResolveReference), ctx, source, target)
}
