// Code generated by MockGen. DO NOT EDIT.
// Source: delivery.go
//
// Generated by this command:
//
//	mockgen -source=delivery.go -destination=mocks.go -package=delivery
//

// Package delivery is a generated GoMock package.
package delivery

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTransport is a mock of Transport interface.
type MockTransport struct {
	ctrl     *gomock.Controller
	recorder *MockTransportMockRecorder
	isgomock struct{}
}

// MockTransportMockRecorder is the mock recorder for MockTransport.
type MockTransportMockRecorder struct {
	mock *MockTransport
}

// NewMockTransport creates a new mock instance.
func NewMockTransport(ctrl *gomock.Controller) *MockTransport {
	mock := &MockTransport{ctrl: ctrl}
	mock.recorder = &MockTransportMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransport) EXPECT() *MockTransportMockRecorder {
	return m.recorder
}

// ID mocks base method.
func (m *MockTransport) ID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockTransportMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockTransport)(nil).ID))
}

// Send mocks base method.
func (m *MockTransport) Send(ctx context.Context, text string) (Receipt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, text)
	ret0, _ := ret[0].(Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockTransportMockRecorder) Send(ctx, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockTransport)(nil).Send), ctx, text)
}

// MockEditor is a mock of Editor interface.
type MockEditor struct {
	ctrl     *gomock.Controller
	recorder *MockEditorMockRecorder
	isgomock struct{}
}

// MockEditorMockRecorder is the mock recorder for MockEditor.
type MockEditorMockRecorder struct {
	mock *MockEditor
}

// NewMockEditor creates a new mock instance.
func NewMockEditor(ctrl *gomock.Controller) *MockEditor {
	mock := &MockEditor{ctrl: ctrl}
	mock.recorder = &MockEditorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEditor) EXPECT() *MockEditorMockRecorder {
	return m.recorder
}

// Edit mocks base method.
func (m *MockEditor) Edit(ctx context.Context, receipt Receipt, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Edit", ctx, receipt, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// Edit indicates an expected call of Edit.
func (mr *MockEditorMockRecorder) Edit(ctx, receipt, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Edit", reflect.TypeOf((*MockEditor)(nil).Edit), ctx, receipt, text)
}

// MockEditableTransport is a mock of EditableTransport interface.
type MockEditableTransport struct {
	ctrl     *gomock.Controller
	recorder *MockEditableTransportMockRecorder
	isgomock struct{}
}

// MockEditableTransportMockRecorder is the mock recorder for MockEditableTransport.
type MockEditableTransportMockRecorder struct {
	mock *MockEditableTransport
}

// NewMockEditableTransport creates a new mock instance.
func NewMockEditableTransport(ctrl *gomock.Controller) *MockEditableTransport {
	mock := &MockEditableTransport{ctrl: ctrl}
	mock.recorder = &MockEditableTransportMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEditableTransport) EXPECT() *MockEditableTransportMockRecorder {
	return m.recorder
}

// Edit mocks base method.
func (m *MockEditableTransport) Edit(ctx context.Context, receipt Receipt, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Edit", ctx, receipt, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// Edit indicates an expected call of Edit.
func (mr *MockEditableTransportMockRecorder) Edit(ctx, receipt, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Edit", reflect.TypeOf((*MockEditableTransport)(nil).Edit), ctx, receipt, text)
}

// ID mocks base method.
func (m *MockEditableTransport) ID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockEditableTransportMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockEditableTransport)(nil).ID))
}

// Send mocks base method.
func (m *MockEditableTransport) Send(ctx context.Context, text string) (Receipt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, text)
	ret0, _ := ret[0].(Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockEditableTransportMockRecorder) Send(ctx, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockEditableTransport)(nil).Send), ctx, text)
}
